### ISSUE TITLE
Replay vs Continue

### ISSUE THREAD

**Issue by daebwae** [rfcx/rfcx-client-stream-ios#10]
When I listen to recording A for 5 minutes, then I switch to recording B and back to recording A. Should we (1) continue where we left off, (2) continue where we have left off but add a restart button, (3) just restart from the beginning ?

Currently we are using (3), but maybe (2) would might be a good idea? Doesn't have to happen in the first version, just putting the idea out there.

**Comment by antonyharfield** [comment]
Good point. I think it is probably not too difficult to keep some extra data about the last position that a user played up until for each stream. This leads into a question of whether we should let the user fast-forward/backwards (skim) through the audio. I think the UI for this is quite difficult if we don't know exactly when the stream should end... Did you solve this on the web player?

**Comment by antonyharfield** [comment]
We have a reasonable strategy for this since our discussion last week and as will be implemented in the "rewind" task.
