### ISSUE TITLE
smooth transition between two sound files

### ISSUE THREAD

**Issue by Starsonic007** [rfcx/rfcx-client-stream-ios#2]
Stream stops after 90 sec suddenly
If a stream is terminated after 90 sec it stops abruptly, and a new one stream begins.
There should be a smooth transition between two sound files.

**Comment by antonyharfield** [comment]
Made some improvements to the gapless play today...

Testing Educador stream there is still a tiny blip between tracks, but I can't tell if this is due to the files or the streamer... It is better than it was before.
